---
- name: Playbook that installs and deploys SunCavanaugh app
  hosts: all
  collections:
    - containers.podman
    - ansible.posix
  roles:
    - wave.config_management.rhel
    - wave.config_management.app
