---
- name: remove container
  containers.podman.podman_container:
    name: colors
    state: absent

- name: Pause for 5 seconds ensuring firewall settings in place
  ansible.builtin.pause:
    seconds: 5

- name: Create the SunCavanaugh application
  containers.podman.podman_container:
    name: colors
    image: quay.io/acme_corp/eda-app:suncavanaugh
    state: started
    recreate: true
    ports:
        - "{{ host_port }}:{{ container_port }}"
    env:
        APP_COLOR: "{{ color }}"
  register: container

- name: Print SunCavanaugh container information
  ansible.builtin.debug:
    var: container
