---
- name: Check if the colors container exists
  containers.podman.podman_container_info:
    name: colors
  register: container_info
  ignore_errors: true

- name: remove container
  containers.podman.podman_container:
    name: colors
    state: stopped
  when: container_info.containers|length > 0
  
- name: remove container
  containers.podman.podman_container:
    name: colors
    state: absent
  when: container_info.containers|length > 0

- name: Pause for 5 seconds to apply fw rules
  ansible.builtin.pause:
    seconds: 5

- name: Create the Globo Financial application
  containers.podman.podman_container:
    name: colors
    image: quay.io/acme_corp/globo-financial:latest
    state: started
    recreate: true
    ports:
        - "{{ host_port }}:{{ container_port }}"
    env:
        APP_COLOR: "{{ color }}"
  register: container

- name: Curl URL of Globo Financial application
  ansible.builtin.uri:
    url: "http://localhost:{{ host_port }}"
    return_content: yes
