---
- name: stop container
  containers.podman.podman_container:
    name: colors
    state: stopped
    image: quay.io/acme_corp/globo-financial:latest
  delegate_to: wave-rhel01-sc02

- name: remove container
  containers.podman.podman_container:
    name: colors
    state: absent
    image: quay.io/acme_corp/globo-financial:latest
    force_delete: true
  delegate_to: wave-rhel01-sc02
