---
#- name: Check if the colors container exists
#  containers.podman.podman_container_info:
#    name: colors
#  register: container_info
#  delegate_to: wave-rhel01-sc02
#  ignore_errors: true

- name: Stop the Podman container
  ansible.builtin.shell: podman stop colors
  delegate_to: wave-rhel01-sc02
 # when: container_info.containers|length > 0

- name: Remove the Podman container
  ansible.builtin.shell: podman rm colors
  delegate_to: wave-rhel01-sc02
 # when: container_info.containers|length > 0
