---
- name: Stop the Podman container
  ansible.builtin.shell: podman stop colors
  delegate_to: wave-rhel01-sc02
  become: true

- name: Remove the Podman container
  ansible.builtin.shell: podman rm colors
  delegate_to: wave-rhel01-sc02
  become: true
