---
- name: Find the container ID of the colors container
  ansible.builtin.shell: podman ps -a --format "{{.ID}}" --filter "name=colors"
  register: container_id
  ignore_errors: true
  delegate_to: wave-rhel01-sc02

- name: Debug container_id
  ansible.builtin.debug:
    var: container_id
  delegate_to: wave-rhel01-sc02

- name: Stop the container if it exists
  ansible.builtin.shell: podman stop {{ container_id.stdout }}
  when: container_id.stdout != ""
  delegate_to: wave-rhel01-sc02

- name: Remove the container if it exists
  ansible.builtin.shell: podman rm {{ container_id.stdout }}
  when: container_id.stdout != ""
  delegate_to: wave-rhel01-sc02

