---
- name: Check if the colors container exists
  containers.podman.podman_container_info:
    name: colors
  register: container_info
  delegate_to: wave-rhel01-sc02
  ignore_errors: true

- name: remove container
  containers.podman.podman_container:
    name: colors
    state: stopped
  delegate_to: wave-rhel01-sc02
  when: container_info.containers|length > 0
  
- name: remove container
  containers.podman.podman_container:
    name: colors
    state: absent
  delegate_to: wave-rhel01-sc02
  when: container_info.containers|length > 0
