- name: setup path
  ansible.builtin.template:
    src: path.j2
    dest: /etc/systemd/system/{{ path_name }}.path
    owner: root
    group: root
    mode: 644
  become: true
 
- name: setup service
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: root
    group: root
    mode: 644
  become: true


- name: activate systemd units
  ansible.builtin.service:
    name: "{{ path_name }}.service"
    state: started
    enabled: yes
  become: true
