---
- name: Install packages required for webserver and firewalld
  ansible.builtin.package:
    name:
      - firewalld
      - httpd
    state: present
  become: true

- name: Enable and start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  become: true

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Configure firewalld ports
  ansible.posix.firewalld:
    port: "80/tcp"
    permanent: true
    state: enabled
    zone: "public"
    immediate: true

- name: Check if the index.html file exists
  ansible.builtin.stat:
    path: "/var/www/html/index.html"
  register: index_html_stat

- name: Install Web application
  ansible.builtin.template: 
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    owner: "apache"
    group: "apache"
    mode: "0644"
  when: not index_html_stat.stat.exists

